export const baseurl = import.meta.env.BASE_URL
export const isNotProduction = Boolean(import.meta.env.PUBLIC_IS_NOT_PRODUCTION)
export const corsAllowOrigin = (isNotProduction) ? "*" : import.meta.env.SITE
export const posturl = baseurl + "app/"
export const abouturl = baseurl + "about/"
export const qaurl = baseurl + "qa/"
export const changeurl = baseurl + "changelog/"
export const policyurl = baseurl + "privacypolicy/"
export const featureurl = baseurl + "feature/"
