export const baseurl = import.meta.env.BASE_URL
export const siteurl = import.meta.env.SITE
export const github_url = "https://github.com/nkte8/skyshare"
export const zenn_profile = "https://zenn.dev/nkte8"
export const zenn_url = "https://zenn.dev/nkte8/articles/2024-02-03-r01"
export const posturl = baseurl + "app/"
export const abouturl = baseurl + "about/"
export const pagesPrefix = "posts"
export const servicename = "Skyshare"
